// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `digitizer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <digitizer.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Device__Digitizer__instantValues_name = "instantValues";

const ::std::string __Device__Digitizer__setTrigEn_name = "setTrigEn";

const ::std::string __Device__Digitizer__values_name = "values";

}
::IceProxy::Ice::Object* ::IceProxy::Device::upCast(::IceProxy::Device::Digitizer* p) { return p; }

void
::IceProxy::Device::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Device::Digitizer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Device::Digitizer;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::Device::Digitizer::instantValues(::Ice::Double& __p_workV, ::Ice::Double& __p_workI, ::Ice::Double& __p_probeV, ::Ice::Double& __p_probeI, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__Device__Digitizer__instantValues_name);
    ::IceInternal::Outgoing __og(this, __Device__Digitizer__instantValues_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    bool __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_workV);
    __is->read(__p_workI);
    __is->read(__p_probeV);
    __is->read(__p_probeI);
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::begin_instantValues(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Device__Digitizer__instantValues_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Device__Digitizer__instantValues_name, __del, __cookie);
    try
    {
        __result->prepare(__Device__Digitizer__instantValues_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::__begin_instantValues(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
            ::Ice::Double __p_workV;
            ::Ice::Double __p_workI;
            ::Ice::Double __p_probeV;
            ::Ice::Double __p_probeI;
            bool __ret;
            try
            {
                __ret = __proxy->end_instantValues(__p_workV, __p_workI, __p_probeV, __p_probeI, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret, __p_workV, __p_workI, __p_probeV, __p_probeI);
            }
        }
    
    private:
        
        ::std::function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)> _response;
    };
    return begin_instantValues(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

bool
IceProxy::Device::Digitizer::end_instantValues(::Ice::Double& __p_workV, ::Ice::Double& __p_workI, ::Ice::Double& __p_probeV, ::Ice::Double& __p_probeI, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Device__Digitizer__instantValues_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_workV);
    __is->read(__p_workI);
    __is->read(__p_probeV);
    __is->read(__p_probeI);
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

bool
IceProxy::Device::Digitizer::setTrigEn(bool __p_en, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__Device__Digitizer__setTrigEn_name);
    ::IceInternal::Outgoing __og(this, __Device__Digitizer__setTrigEn_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_en);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    bool __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::begin_setTrigEn(bool __p_en, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Device__Digitizer__setTrigEn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Device__Digitizer__setTrigEn_name, __del, __cookie);
    try
    {
        __result->prepare(__Device__Digitizer__setTrigEn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_en);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::__begin_setTrigEn(bool __p_en, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
            bool __ret;
            try
            {
                __ret = __proxy->end_setTrigEn(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (bool)> _response;
    };
    return begin_setTrigEn(__p_en, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

bool
IceProxy::Device::Digitizer::end_setTrigEn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Device__Digitizer__setTrigEn_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

bool
IceProxy::Device::Digitizer::values(::Factory::TDoubleArray& __p_workV, ::Factory::TDoubleArray& __p_workI, ::Factory::TDoubleArray& __p_probeV, ::Factory::TDoubleArray& __p_probeI, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__Device__Digitizer__values_name);
    ::IceInternal::Outgoing __og(this, __Device__Digitizer__values_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    bool __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_workV);
    __is->read(__p_workI);
    __is->read(__p_probeV);
    __is->read(__p_probeI);
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::begin_values(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Device__Digitizer__values_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Device__Digitizer__values_name, __del, __cookie);
    try
    {
        __result->prepare(__Device__Digitizer__values_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::__begin_values(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
            ::Factory::TDoubleArray __p_workV;
            ::Factory::TDoubleArray __p_workI;
            ::Factory::TDoubleArray __p_probeV;
            ::Factory::TDoubleArray __p_probeI;
            bool __ret;
            try
            {
                __ret = __proxy->end_values(__p_workV, __p_workI, __p_probeV, __p_probeI, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret, __p_workV, __p_workI, __p_probeV, __p_probeI);
            }
        }
    
    private:
        
        ::std::function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)> _response;
    };
    return begin_values(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

bool
IceProxy::Device::Digitizer::end_values(::Factory::TDoubleArray& __p_workV, ::Factory::TDoubleArray& __p_workI, ::Factory::TDoubleArray& __p_probeV, ::Factory::TDoubleArray& __p_probeI, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Device__Digitizer__values_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_workV);
    __is->read(__p_workI);
    __is->read(__p_probeV);
    __is->read(__p_probeI);
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::Device::Digitizer::ice_staticId()
{
    return ::Device::Digitizer::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Device::Digitizer::__newInstance() const
{
    return new Digitizer;
}

::Ice::Object* Device::upCast(::Device::Digitizer* p) { return p; }

namespace
{
const ::std::string __Device__Digitizer_ids[3] =
{
    "::Device::Digitizer",
    "::Factory::DeviceAbs",
    "::Ice::Object"
};

}

bool
Device::Digitizer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Device__Digitizer_ids, __Device__Digitizer_ids + 3, _s);
}

::std::vector< ::std::string>
Device::Digitizer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Device__Digitizer_ids[0], &__Device__Digitizer_ids[3]);
}

const ::std::string&
Device::Digitizer::ice_id(const ::Ice::Current&) const
{
    return __Device__Digitizer_ids[0];
}

const ::std::string&
Device::Digitizer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Device::Digitizer";
    return typeId;
#else
    return __Device__Digitizer_ids[0];
#endif
}

::Ice::DispatchStatus
Device::Digitizer::___instantValues(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Ice::Double __p_workV;
    ::Ice::Double __p_workI;
    ::Ice::Double __p_probeV;
    ::Ice::Double __p_probeI;
    bool __ret = instantValues(__p_workV, __p_workI, __p_probeV, __p_probeI, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__p_workV);
    __os->write(__p_workI);
    __os->write(__p_probeV);
    __os->write(__p_probeI);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Device::Digitizer::___setTrigEn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    bool __p_en;
    __is->read(__p_en);
    __inS.endReadParams();
    bool __ret = setTrigEn(__p_en, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Device::Digitizer::___values(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Factory::TDoubleArray __p_workV;
    ::Factory::TDoubleArray __p_workI;
    ::Factory::TDoubleArray __p_probeV;
    ::Factory::TDoubleArray __p_probeI;
    bool __ret = values(__p_workV, __p_workI, __p_probeV, __p_probeI, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__p_workV);
    __os->write(__p_workI);
    __os->write(__p_probeV);
    __os->write(__p_probeI);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Device__Digitizer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "instantValues",
    "release",
    "setTrigEn",
    "status",
    "values"
};

}

::Ice::DispatchStatus
Device::Digitizer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Device__Digitizer_all, __Device__Digitizer_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Device__Digitizer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___instantValues(in, current);
        }
        case 5:
        {
            return ___release(in, current);
        }
        case 6:
        {
            return ___setTrigEn(in, current);
        }
        case 7:
        {
            return ___status(in, current);
        }
        case 8:
        {
            return ___values(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Device::Digitizer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Device::Digitizer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Device::__patch(DigitizerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Device::DigitizerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Device::Digitizer::ice_staticId(), v);
    }
}
